using System.ComponentModel.DataAnnotations;

namespace Espresso.Domain.Enums.NewsPortalEnums
{
    public enum NewsPortalId
    {
        [Display(Name = "Undefined")]
        Undefined = 0,
        [Display(Name = "Index.hr")]
        Index = 1,
        [Display(Name = "24 sata")]
        DvadesetCetiriSata = 2,
        [Display(Name = "Sportske Novosti")]
        SportskeNovosti = 3,
        [Display(Name = "Jutarnji List")]
        JutarnjiList = 4,
        [Display(Name = "Net.hr")]
        NetHr = 5,
        [Display(Name = "Slobodna Dalmacija")]
        SlobodnaDalmacija = 6,
        [Display(Name = "tportal")]
        TPortal = 7,
        [Display(Name = "Večernji List")]
        VecernjiList = 8,
        [Display(Name = "Telegram")]
        Telegram = 9,
        [Display(Name = "Dnevnik")]
        Dnevnik = 10,
        [Display(Name = "Gol")]
        Gol = 11,
        [Display(Name = "RTL Vijesti")]
        RtlVijesti = 12,
        [Display(Name = "News Bar")]
        NewsBar = 14,
        [Display(Name = "Nogomet Plus")]
        NogometPlus = 15,
        [Display(Name = "Lider")]
        Lider = 16,
        [Display(Name = "Poslovni Dnevnik")]
        PoslovniDnevnik = 17,
        [Display(Name = "Bug")]
        Bug = 18,
        [Display(Name = "Vidi.hr")]
        VidiHr = 19,
        [Display(Name = "Zimo")]
        Zimo = 20,
        [Display(Name = "Netokracija")]
        Netokracija = 21,
        [Display(Name = "Poslovni Puls")]
        PoslovniPuls = 22,
        [Display(Name = "PCchip")]
        PcChip = 23,
        [Display(Name = "Cosmopolitan")]
        Cosmopolitan = 25,
        [Display(Name = "Wall.hr")]
        WallHr = 26,
        [Display(Name = "Ljepota i zdravlje")]
        LjepotaIZdravlje = 27,
        [Display(Name = "Autonet")]
        Autonet = 28,
        [Display(Name = "N1")]
        N1 = 29,
        [Display(Name = "Narod HR")]
        NarodHr = 30,
        [Display(Name = "HRT")]
        Hrt = 31,
        [Display(Name = "100posto")]
        StoPosto = 32,
        [Display(Name = "Dnevno.Hr")]
        Dnevno = 33,
        [Display(Name = "Automobili.hr")]
        AutomobiliHr = 34,
        [Display(Name = "Direktno")]
        DirektnoHr = 35,
        [Display(Name = "Scena")]
        Scena = 36,
        [Display(Name = "Dalmacija Danas")]
        DalmacijaDanas = 37,
        [Display(Name = "Nacional")]
        Nacional = 38,
        [Display(Name = "Express")]
        Express = 39,
        [Display(Name = "Dalmacija News")]
        DalmacijaNews = 40,
        [Display(Name = "Dalmatinski Portal")]
        DalmatinskiPortal = 41,
        [Display(Name = "Kultur Istra")]
        KulturIstra = 42,
        [Display(Name = "iPazin")]
        IPazin = 43,
        [Display(Name = "Novi list")]
        NoviList = 44,
        [Display(Name = "Parentium")]
        Parentium = 45,
        [Display(Name = "Lika Klub")]
        LikaKlub = 46,
        [Display(Name = "Lika express")]
        LikaExpress = 47,
        [Display(Name = "Lika Online")]
        LikaOnline = 48,
        [Display(Name = "Lika plus")]
        LikaPlus = 49,
        [Display(Name = "Index.Hr - Zagreb")]
        IndexHrZagreb = 50,
        [Display(Name = "Zagreb Info")]
        ZagrebInfo = 51,
        [Display(Name = "Zagrebancija")]
        Zagrebancija = 52,
        [Display(Name = "Sjever.hr")]
        SjeverHr = 53,
        [Display(Name = "Prigorski.hr")]
        PrigorskiHr = 54,
        [Display(Name = "ePodravina.hr")]
        PodravinaHr = 55,
        [Display(Name = "Baranja info")]
        BaranjaInfo = 56,
        [Display(Name = "Glas Slavonije")]
        GlasSlavonije = 57,
        [Display(Name = "Slavonski Hr")]
        SlavonskiHr = 58,
        [Display(Name = "iVijesti")]
        IVijesti = 59,
        [Display(Name = "Dubrovački Dnevnik.hr")]
        DubrovackiDnevnik = 60,
        [Display(Name = "Istarska Županija")]
        IstarskaZupanija = 61,
        [Display(Name = "Zagreb Online")]
        ZagrebOnline = 62,
        [Display(Name = "Sisak.Info")]
        SisakInfo = 63,
        [Display(Name = "Osijek NEWS")]
        OsijekNews = 64,
        [Display(Name = "Slobodna Dalmacija - Dalmacija")]
        SlobodnaDalmacija_Dalmacija = 65,
        [Display(Name = "Slobodna Dalmacija - Split")]
        SlobodnaDalmacija_Split = 66,
        [Display(Name = "Dubrovniknet.hr")]
        DubrovnikNet = 67,
        [Display(Name = "MakarskaDanas")]
        MakarskaDanas = 68,
        [Display(Name = "Makarska")]
        MakarskaHr = 69,
        [Display(Name = "Portaloko.hr")]
        PortalOko = 70,
        [Display(Name = "Antena portal Zadar")]
        AntenaZadar = 71,
        [Display(Name = "Radio Imotski")]
        RadioImotski = 72,
        [Display(Name = "Imotske Novine")]
        ImotskeNovine = 73,
        [Display(Name = "Portal Grada Kaštela")]
        PortalKastela = 74,
        [Display(Name = "Huknet")]
        HukNet = 75,
        [Display(Name = "Zadarski List")]
        ZadarskiList = 76,
        [Display(Name = "Istra Terra Magica")]
        IstraTerraMagica = 77,
        [Display(Name = "iPress")]
        IPress = 78,
        [Display(Name = "Rijeka Danas")]
        RijekaDanas = 80,
        [Display(Name = "Fiuman")]
        Fiuman = 81,
        [Display(Name = "Riportal")]
        Riportal = 82,
        [Display(Name = "GS Press")]
        GsPress = 83,
        [Display(Name = "Zagrebački List")]
        ZagrebackiList = 84,
        [Display(Name = "ZG portal")]
        ZgPortal = 85,
        [Display(Name = "Grad Zagreb")]
        GradZagreb = 86,
        [Display(Name = "7Plus Regionalni Tjednik")]
        PlusRegionalniTjednik = 87,
        [Display(Name = "Glas Podravine i Prigorja")]
        GlasPodravineIPrigorja = 88,
        [Display(Name = "Međimurje Info")]
        MedimurjeInfo = 89,
        [Display(Name = "Međimurske Novine")]
        MedimurskeNovine = 90,
        [Display(Name = "Zagorje.com")]
        ZagorjeCom = 91,
        [Display(Name = "Informativni Centar Virovitica")]
        InformativniCentarVirovitica = 92,
        [Display(Name = "Novska.IN")]
        NovskaIn = 93,
        [Display(Name = "Novosti.hr")]
        NovostiHr = 94,
        [Display(Name = "Portal53")]
        Portal53 = 95,
        [Display(Name = "SBplus.hr")]
        SbPlusHr = 96,
        [Display(Name = "Požeška Kronika")]
        PozeskaKronika = 97,
        [Display(Name = "Osijek031")]
        Osijek031 = 98,
        [Display(Name = "Otvoreno.hr")]
        OtvorenoHr = 99,
        [Display(Name = "Geopolitika News")]
        GeoPolitika = 100,
        [Display(Name = "Povijest.hr")]
        PovijestHr = 101,
        [Display(Name = "7dnevno")]
        Dnevno7 = 102,
        [Display(Name = "Basketball.hr")]
        BasketballHr = 103,
        [Display(Name = "JoomBoos")]
        JoomBoos = 104,
        [Display(Name = "ICT Business")]
        IctBusiness = 105,
        [Display(Name = "HCL Gaming Portal")]
        Hcl = 106,
        [Display(Name = "Profitiraj.hr")]
        ProfitirajHr = 107,
        [Display(Name = "motori.hr")]
        MotoriHr = 108,
        [Display(Name = "Autoportal.hr")]
        AutoportalHr = 109,
        [Display(Name = "AutopressHR")]
        AutopressHr = 110,
        [Display(Name = "Vozim.HR")]
        VozimHr = 111,
        [Display(Name = "AUTO MOTOR I SPORT")]
        AutoMotorSport = 112,
        [Display(Name = "Hoopster.hr")]
        Hoopster = 113,
        [Display(Name = "Hrvatski Telekom Prva liga")]
        PrvaHnl = 114,
        [Display(Name = "Al Jazeera Balkans")]
        AlJazeera = 115,
        [Display(Name = "hifimedia")]
        HifiMedia = 116,
        [Display(Name = "Geek.hr")]
        GeekHr = 117,
        [Display(Name = "vizkultura.hr")]
        VizKultura = 118,
        [Display(Name = "Život umjetnosti")]
        ZivotUmjetnosti = 119,
        [Display(Name = "SVIJET KULTURE")]
        SvijetKulture = 120,
        [Display(Name = "Gamer.hr")]
        GamerHr = 121,
        [Display(Name = "OG Portal")]
        OgPortal = 122,
        [Display(Name = "Županjac.net")]
        Zupanjac = 123,
        [Display(Name = "PRESS 032")]
        Press032 = 124,
        [Display(Name = "Bitno.net")]
        BitnoNet = 125,
        [Display(Name = "Ploče Online")]
        PloceOnline = 126,
        [Display(Name = "KAportal.hr")]
        KaPortalHr = 127,
        [Display(Name = "Radio Mrežnica")]
        RadioMreznica = 128
    }
}
