# Managed instance groups backing each workload.
#
# Two MIGs: webapi (autoscaled, europe-west3-c) and dashboard (single instance,
# us-east1-b — pinned to the GCP always-free zone). The legacy espresso-app MIG
# was decommissioned out-of-band.

resource "google_compute_instance_group_manager" "webapi" {
  name               = "espresso-web-api-instance-group"
  zone               = var.webapi_zone
  base_instance_name = "espresso-web-api-instance-group"

  version {
    instance_template = google_compute_instance_template.webapi.id
  }

  named_port {
    name = "http"
    port = 80
  }

  auto_healing_policies {
    health_check      = google_compute_health_check.readiness.id
    initial_delay_sec = 30
  }

  instance_lifecycle_policy {
    default_action_on_failure = "REPAIR"
    force_update_on_repair    = "NO"
  }

  update_policy {
    minimal_action        = "REPLACE"
    type                  = "PROACTIVE"
    max_surge_fixed       = 1
    max_unavailable_fixed = 0
    replacement_method    = "SUBSTITUTE"
  }

  # `version[0].name` is auto-generated by GCP (timestamp-based) each time the
  # MIG is updated. Ignoring it so TF doesn't repeatedly try to null it out.
  lifecycle {
    ignore_changes = [version[0].name]
  }
}

resource "google_compute_autoscaler" "webapi" {
  name   = "espresso-web-api-instance-group"
  zone   = var.webapi_zone
  target = google_compute_instance_group_manager.webapi.id

  autoscaling_policy {
    min_replicas    = 1
    max_replicas    = 2
    cooldown_period = 30
    mode            = "ON"

    cpu_utilization {
      target = 0.9
    }

    scale_in_control {
      time_window_sec = 600

      max_scaled_in_replicas {
        fixed = 1
      }
    }
  }
}

resource "google_compute_instance_group_manager" "dashboard" {
  name               = "espresso-dashboard-instance-group"
  zone               = var.dashboard_zone
  base_instance_name = "espresso-dashboard-instance-group"
  description        = "US free tier"

  version {
    instance_template = google_compute_instance_template.dashboard.id
  }

  named_port {
    name = "http"
    port = 80
  }

  auto_healing_policies {
    health_check      = google_compute_health_check.liveness.id
    initial_delay_sec = 180
  }

  instance_lifecycle_policy {
    default_action_on_failure = "REPAIR"
    force_update_on_repair    = "NO"
  }

  # Dashboard cannot SUBSTITUTE (would need a second e2-micro instance briefly,
  # and the static external IP / free-tier constraints make that fragile),
  # so the policy is in-place RECREATE.
  update_policy {
    minimal_action        = "REPLACE"
    type                  = "PROACTIVE"
    max_surge_fixed       = 0
    max_unavailable_fixed = 1
    replacement_method    = "RECREATE"
  }

  lifecycle {
    ignore_changes = [version[0].name]
  }
}
